# default_config.yaml
defaults:
  model:
    hyperparameter_mode: "auto"
    version_history: 3
    training_period:
      auto_range:
        lookback_period: "30d"
        step: "1m"
    retrain:
      enabled: false
  
  system:
    points_retention: "30d"
    cleanup_interval: "1d"